### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by neverke1** [abearcodes/Valheim#11]
![image](https://user-images.githubusercontent.com/68199224/109445542-16908e00-7a40-11eb-81ef-d5f4e14900dc.png)

This can't be good :o right on the start screen

**Comment by abearcodes** [comment]
Woops :) Mod should still work even with these errors on the main screen. That said, v0.0.2 with a fix for this is out :) Please reopen if the issue persists
