### ISSUE TITLE
Fueling Not Functioning Properly

### ISSUE THREAD

**Issue by rcayne** [abearcodes/Valheim#16]
Hi there!

I'm a fan of your CraftWithContainers mod and I've recently encountered a problem.
It seems I'm no longer able to fuel my Charcoal Kiln with wood from my nearby chests, nor am I able to fill my Smelter with ores. 
I am still able to fuel my campfires with nearby wood, and fueling the smelter with coal is still functioning, but everything else seems to have stopped working. 

Let me know if this is an issue or if it is something that's no longer included with your mod/was never meant to be present. 

Thank you for your great work!

**Comment by abearcodes** [comment]
I will look into it the next time I have some time for modding.  It is something that is expected to work :)

**Comment by normous** [comment]
Confirming behavior as stated by rcayne.  

@abearcodes:  thank you for your mods!  Your work is much appreciated by everyone on my server.

**Comment by abearcodes** [comment]
Fixed in 1.0.8
