### ISSUE TITLE
[CraftingWithContainers] Feature Request: Reverse container item removal

### ISSUE THREAD

**Issue by Qrylor** [abearcodes/Valheim#17]
If easy to implement, add an option to remove items from chests in revers automatic input order.
Every-time I open a sorted chest (left to right), the partial or lack of stacks in the first positions (using default stack insertion into the chest) keeps causing OCD issues.

Appreciation of the continued mod support.

**Comment by abearcodes** [comment]
Done. Should work with both furnaces/kilns and crafting. Will be released in the next version

**Comment by abearcodes** [comment]
Released in 1.0.8

**Comment by Qrylor** [comment]
So much better, appreciations for the work and unexpectedly quick implementation.
