### ISSUE TITLE
[SimpleRecycling] Receiving extra items when RecyclingRate = 1.0

### ISSUE THREAD

**Issue by korocota** [abearcodes/Valheim#20]
Found this bug by pure chance helping some guy who asked how to get back 100% of mats.

How to reproduce:

- RecyclingRate = 1.0 
- Craft Wooden Club (costs wood x6)
  
- Uncraft Wooden Club (you get back woodx6, bone fragments x1)

**Comment by abearcodes** [comment]
Confirmed. Looking into ti

**Comment by abearcodes** [comment]
Fixed as of 0.0.7, released on both Nexus and Thunderstore
