### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by gembrosy** [abearcodes/Valheim#24]
I got this error with the mod version 0.0.8. The game starts without the mod. No other mods are installed. Version 0.0.7 works fine

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> ABearCodes.Valheim.SimpleRecycling.UI.InventoryGuiPatches.InventorySave (Inventory __instance) (at <3f20fcc0009f4b30b075ee1f5f98ce9c>:0)
> (wrapper dynamic-method) Inventory.DMD<Inventory::Changed>(Inventory)
> Inventory.AddItem (ItemDrop+ItemData item, System.Int32 amount, System.Int32 x, System.Int32 y) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> Inventory.AddItem (System.String name, System.Int32 stack, System.Single durability, Vector2i pos, System.Boolean equiped, System.Int32 quality, System.Int32 variant, System.Int64 crafterID, System.String crafterName) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> Inventory.Load (ZPackage pkg) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> Player.Load (ZPackage pkg) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> PlayerProfile.LoadPlayerData (Player player) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> FejdStartup.SetupCharacterPreview (PlayerProfile profile) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> FejdStartup.UpdateCharacterList () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> FejdStartup.SetSelectedProfile (System.String filename) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
> (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

**Comment by abearcodes** [comment]
Thank you for the report! Fixed in 0.0.9. Please reopen if the issue resurfaces.
