### ISSUE TITLE
Add a feature to restrict fuel options from auto-pull process

### ISSUE THREAD

**Issue by SirFrostingham** [abearcodes/Valheim#25]
**Which mod are you proposing a feature for?**
Crafting With Containers

**Is your feature request related to a problem? Please describe.**
On my server, we separate fine wood to its own chest. Various things around the base are auto-pulling fine wood and core wood as fuel, We would like to restrict the options to ONLY regular wood. To workaround this issue, the only real option we have is to turn off these 2 settings: 
- AllowTakeFuelForKilnAndFurnace
- AllowTakeFuelForFireplace

**Describe the solution you'd like**
A nice solution would be to add either an exclusion list or an inclusive list.
Exclusion list example (This is maybe preferred, since if you want to exclude something, you just add it): 
RestrictedFuelClassNames = Finewood, RoundLog
   - OR
Inclusive list example:
AllowedFuelClassNames = Wood

**Additional context**
Nothing else to add, besides this is a REALLY great mod... So is your Recycle Items mod!

**Comment by abearcodes** [comment]
Thank you for the proposal and for using the mod! 

Totally understandable. I'll look into it once I can dedicate time to modding (most likely coming weekend), should be fairly easy! 

I think I'll go for a whitelist with only wood included by default like you proposed. Stay tuned

**Comment by SirFrostingham** [comment]
Thank you so much! Very excited. :)

**Comment by abearcodes** [comment]
Added in 1.0.10, now allows to use "Wood" only by default. Please reopen if something is missing!
