### ISSUE TITLE
Multicraft + CWC Interaction Fix

### ISSUE THREAD

**Issue by GalacticRuler** [abearcodes/Valheim#28]
**Which mod are you proposing a feature for?**
Crafting With Containers

**Is your feature request related to a problem? Please describe.**
Mod is partially incompatible with Multicraft; the competitor/sister mod CIC works fine but this one (which I'd like to keep using) breaks slightly and inconsistently

**Describe the solution you'd like**
Would simply like the problem to be fixed (currently partially breaks the container searching, causing it to display X/0 for everything but still allows crafting as if it was working). This stops Multicraft's math from working and caps number of items to craft to 1. That dev has directed people here from the Nexus, otherwise I'd've asked them.

**Additional context**
Technically this is a bug, but I feel like it's a back-burner kind of thing as it is harmless, if irritating

**Comment by abearcodes** [comment]
Aha. CwC not being on Nexus does have the downside of there being no community discussions and me being clueless as to what the hell is going on with weird interactions like these, so thank you for sharing! 

What I try to avoid within my mods is copy pasting functionality from the base game as this makes it a maintanability nightmare when patches roll out. In some cases, when it’s a completely new addition (like the crafting tab for Simple Recycling), it makes sense to duplicate the logic, but when it’s modifying an existing behavior, it gets ugly. 

The way CwC worked was at some point in a very similar fashion to how CfC works, but then I decided that doing complete detours of functions and performing checks is not a good thing and went for patching only specific calls to inventory checks in specific places... which ended up being a worse approach for cases like this :)

I’ll test it with Multicraft and see if there’s graceful workarounds, if not, I think I might just rollback that specific part of the code (the place where it actually hooks the calls) to how it worked before. Which would also fix it for other mods

**Comment by abearcodes** [comment]
Fixed in 1.0.10. Please reopen if it keeps happening!
