### ISSUE TITLE
Epic Loot conflict

### ISSUE THREAD

**Issue by heinrich6745** [abearcodes/Valheim#29]
**Mod**: Crafting With Containers / Simple Recycling

I have noticed along with another user on that mods comment page that these two mods conflict for some reason.

https://www.nexusmods.com/valheim/mods/387
https://i.imgur.com/rolGV0W.png
https://i.imgur.com/F8cIDED.png

**Comment by abearcodes** [comment]
Simple Recycling 0.0.11 released that moves the button and fixes some UI issues. Please reopen if you still have issues.
