### ISSUE TITLE
CraftingWithContainers compatibility with Epic Loot 

### ISSUE THREAD

**Issue by BurroTile** [abearcodes/Valheim#31]
Thanks for the mod! Loving it!

Happens randomly when interacting with containers/forge. No problem until Epic loot was installed. Both mods seem to work fine independently.

https://valheim.thunderstore.io/package/abearcodes/CraftingWithContainers/
https://valheim.thunderstore.io/package/RandyKnapp/EpicLoot/

Collected:

[Error : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at :0)
EpicLoot.MagicItem.GetEffectText (EpicLoot.MagicItemEffect effect, EpicLoot.ItemRarity rarity, System.Boolean showRange) (at :0)
EpicLoot.MagicItem.GetTooltip () (at :0)
EpicLoot.MagicItemTooltip_ItemDrop_Patch.Prefix (System.String& __result, ItemDrop+ItemData item, System.Int32 qualityLevel, System.Boolean crafting) (at :0)
(wrapper dynamic-method) ItemDrop+ItemData.DMDItemDrop+ItemData::GetTooltip(ItemDrop/ItemData,int,bool)
ItemDrop+ItemData.GetTooltip () (at :0)
EpicLoot.InventoryGrid_CreateItemTooltip_MagicItemComponent_Patch.Prefix (ItemDrop+ItemData item, UITooltip tooltip) (at :0)
(wrapper dynamic-method) InventoryGrid.DMDInventoryGrid::CreateItemTooltip(InventoryGrid,ItemDrop/ItemData,UITooltip)
(wrapper dynamic-method) InventoryGrid.DMDInventoryGrid::UpdateGui(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at :0)
InventoryGui.UpdateInventory (Player player) (at :0)
InventoryGui.Update () (at :0)

[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ABearCodes.Valheim.CraftingWithContainers.Crafting.UIVisualPatches.PatchDoCraftingHook (Player player, Recipe ___m_craftRecipe) (at <06048c31eab24880b534d5998685a355>:0)
(wrapper dynamic-method) InventoryGui.DMDInventoryGui::DoCrafting(InventoryGui,Player)
(wrapper dynamic-method) InventoryGui.DMDInventoryGui::UpdateRecipe(InventoryGui,Player,single)
InventoryGui.Update () (at :0)

Thanks!

**Comment by abearcodes** [comment]
Fixed in 1.0.10. Please reopen if it keeps happening!
