### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'CraftFromContainers, Version=1.0.0.0, 

### ISSUE THREAD

**Issue by Boatsandlogs** [abearcodes/Valheim#32]
**Mod**: Crafting With Containers 

**Mod Version**:   1.0.9

**Describe the bug**
Doesnt work in game, here is the console code

[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'CraftFromContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**How To Reproduce**
1. Launch the game
2. Look at console, see above error
3. go in game to make sure, mod is not functioning

**Expected behavior**
expected to be able to craft with nearby containers

Mods List:

1 key dodge
Add all fuel
Auto Split Stack
Autofuel
Autopickup Filter
Autostore
Blast furnace all ores
Build Camera
Build near locations
Change forsaken power
Clock Mod
Crop Replant
Custom Container Sizes
Discard Inventory Item
Drop just enough
Equipment and Quick Slots
Expertmode
Faster Teleportation
Faster boats
FireIsHot
First Person view
Floating items
Fog Cloud Smoke
Gravekeeper
Heightmap unlimited
Hook Gen Patcher
Im No Masochist
Improved Build Hud
Improved dverger circlet
InstantMonsterDrop
Interact While Building
Inventory Sort
Invis Helm
Item Stacks
Jump Alters Falling Damage
Last used weapons
Minimal Status Effects
More slots
Movable Chest Inventory
Much better hotkeys
Nexus Update
Pickup World Display
Pin filters
Placement unlocked
Preworkout
Quick Deposit
Quick mining and logging
QuickStack
Skip intro
Sktoolbox
Snap points made easy
Split stack text input
Statslogger
Teleporter Title
Time Mod
Torches Eternal
Unfrighten Tamed Animals
Useful trophies
Valheim Plus
Wind at your back
Wishbone slot
Worldgen options
invis armor

**Comment by abearcodes** [comment]
I can understand how it can get confusing 😄  
Here's a link to the repo of Crafting **_From_** Containers :) 
https://github.com/aedenthorn/ValheimMods
