### ISSUE TITLE
Crafting With Containers UI missing total resources

### ISSUE THREAD

**Issue by rootdarkarchon** [abearcodes/Valheim#35]
In 1.0.10 the UI does not show the total amount of resources anymore. Worked in 1.0.9.

List of mods used:
![image](https://user-images.githubusercontent.com/21534284/111027231-371cf880-83ef-11eb-8440-1e3c0534794e.png)

**Comment by abearcodes** [comment]
Woops! Missed to return a boolean! Hotfixing :)

**Comment by abearcodes** [comment]
Didn't mean to close the ticket so fast. Version 1.0.11 coming right now
