### ISSUE TITLE
Compatibility issue with EpicLoot

### ISSUE THREAD

**Issue by godwings101** [abearcodes/Valheim#37]
Crafting With Containers
EpicLoot by RandyKnapp

**Mod Version**: CraftingWithContainers V 1.0.11
EpicLoot V 0.5.9

**Describe the bug**
When trying to sacrifice an enchanted item at the forge the progress bar for completing the activity fills up but doesn't complete it and defaults the forge screen to upgrading an item not selected. It also makes you have to click an option on the forge in order to exit the forge.

**How To Reproduce**
1. First have the enchanter built for the forge.
2. Then have an enchanted item
3. Try sacrificing the enchanted item for
4. Then this bug happens

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Additional details**
Simple Recycling
Farm Grid
EquipmentAndQuickslots
ItemStacks
UseEquipmentInWater
Locator
Skillful
Preworkout
LocateMerchant
NoStaminaSneak
FloatingItems
Jam
EpicLoot
ExtendedItemDataFramework

**Comment by abearcodes** [comment]
I'm having trouble replicating the issue, but I think I know what causes it. 
Can you try with this version of the mod before I release it?

[ABearCodes.Valheim.CraftingWithContainers.zip](https://github.com/abearcodes/Valheim/files/6135083/ABearCodes.Valheim.CraftingWithContainers.zip)

**Comment by abearcodes** [comment]
Finally replicated locally, it was also quite random. Released Crafting with Containers version 1.0.12. 

Please try it out and let me know if it resurfaces.

**Comment by godwings101** [comment]
That version fixed the issue. Thanks!

**Comment by abearcodes** [comment]
Thanks! Closing the issue
