### ISSUE TITLE
Duplication Bug on Cart

### ISSUE THREAD

**Issue by FelipeBelchior** [abearcodes/Valheim#38]
When I was crafting some ice arrows, I put the freeze glands in the cart and the craft was available in the workbench. But when I clicked to craft the game uses some itens and not the freeze gland. I don't know the exactly what's this bug condition, but maybe that works for some others items as well.

The itens needed to craft the ice arrow in the cart
![Screenshot_102](https://user-images.githubusercontent.com/23386799/111050818-9dc10700-842d-11eb-9911-4d155e8c7f24.png)

My inventory before the craft
![Screenshot_103](https://user-images.githubusercontent.com/23386799/111050945-5edf8100-842e-11eb-91b8-a2bac5880535.png)

After crafting the ice arrow
![Screenshot_104](https://user-images.githubusercontent.com/23386799/111050839-c1844d00-842d-11eb-98d9-2f8e90e0f984.png)

**Comment by abearcodes** [comment]
Thanks for the report! Replicated locallly.  Looking into it!

**Comment by abearcodes** [comment]
Should be fixed as of 1.0.13, if not, please reopen
