### ISSUE TITLE
No longer able to pull ore from container directly in to smelter.

### ISSUE THREAD

**Issue by TheJackalMan** [abearcodes/Valheim#39]
**Mod**: Crafting With Containers

**Mod Version**: 1.0.12

**Describe the bug**
No longer able to pull ore from nearby containers in to the smelter directly

**How To Reproduce**
1. Place ore in container within range of Smelter
2. Press E on smelter intake
3. Game does not detect that you have ore available

**Expected behavior**
Ore previously was detected and usable from container

**Comment by SirFrostingham** [comment]
+1. Auto-pull ore to smelter used to work, but does not anymore. Single player or in dedicated multiplayer server.

**Comment by abearcodes** [comment]
@SirFrostingham, thanks for the report! 

It was a deliberate decision at the time, but I can see how I was a bit hasty with it :) This was part of filtering which wood goes into Kilns, but ended up blocking Smelter crafts too. Next version will have a separate `AllowedFurnaceOres` filter that will be disabled by default.

**Comment by SirFrostingham** [comment]
Thanks for your work. One of the top mods for sure. Game changer!

**Comment by abearcodes** [comment]
Should be fixed as of 1.0.13, if not, please reopen
