### ISSUE TITLE
Maybe Swap out FindObjectsOfType for a sphere cast?

### ISSUE THREAD

**Issue by attckdog** [abearcodes/Valheim#4]
https://github.com/abearcodes/Valheim/blob/68462856692f7307d457d89c3a2d6b9f37b9d235/ABearCodes.Valheim.CraftingWithContainers/Tracking/TrackContainersWhenPlayerUsesCraftingStationPatch.cs#L77

FindObjectsOfType is super heavy call, it searches the entire unity object tree top to bottom.
if the Unity physics is accessible, Could we instead use a sphere cast as the starting search and then make sure it's allowable?

**Comment by abearcodes** [comment]
I do agree that it's a super heavy call. That's also exactly why instead of running it constantly and doing the look up, it just runs once when the player is starting to use the crafting station and they get added to a tracker. I do need to add handlers for destruction and creation of new containers though, created #5 for it. 

I do like your idea. I will try it out when I have the time

**Comment by ManuelSegura** [comment]
I would suggest to use OverlapSphere instead of SphereCast because it's cheaper.

```cs
   List<Containers> GetChests(Vector3 center, float radius)
    {
        List<Containers> chestList = new List<Containers>();

        Collider[] hitColliders = Physics.OverlapSphere(center, radius, 1>>8, QueryTriggerInteraction.Ignore);
        foreach (var col in hitColliders)
        {
            Container isChest = col.GetComponent<Container>();
            if (isChest ) chestList.Add(collider).
        }

        return chestList;
    }
```

Something like that I guess.

**Comment by abearcodes** [comment]
Should be no longer needed. Mod now tracks whenever a new Container component `Awake`s (via Harmony patch) and adds it to a list and iterates when needed. 

For details see: 
https://github.com/abearcodes/Valheim/tree/feature/rewrite/ABearCodes.Valheim.CraftingWithContainers/Tracking

Mainly: 
- [Container lifecycle tracking via Awake](https://github.com/abearcodes/Valheim/blob/feature/rewrite/ABearCodes.Valheim.CraftingWithContainers/Tracking/ContainerLifecyclePatches.cs)
- Simple list within ContainerTracker https://github.com/abearcodes/Valheim/blob/e5f6b9f935ac84b75f2a572af6b571fb0929b8e5/ABearCodes.Valheim.CraftingWithContainers/Tracking/ContainerTracker.cs#L11
- Simple straightforward iteration of said containers https://github.com/abearcodes/Valheim/blob/e5f6b9f935ac84b75f2a572af6b571fb0929b8e5/ABearCodes.Valheim.CraftingWithContainers/Tracking/ContainerTracker.cs#L34-L35

I think this is a better approach than constantly hitting physics and it has proved to be reliable during testing. If you feel like trying it out, see: https://github.com/abearcodes/Valheim/releases/tag/v1.0.4-beta.1

Unless there are reasons not too, I'll proceed with this tracking approach going forward. Let me know what you think.

**Comment by abearcodes** [comment]
Sticking to Awake/Destroy hooks. Closing. 

Thanks everybody for your input!
