### ISSUE TITLE
Show how many items can be built using available resources

### ISSUE THREAD

**Issue by normous** [abearcodes/Valheim#40]
**Which mod are you proposing a feature for?**
Crafting With Containers

**Is your feature request related to a problem? Please describe.**
Since CwC overlaps so much with ImprovedBuildHud, it would be nice if the last bit of remaining functionality were rolled into CwC.  This is a request to show how many items can be built using available resources.

**Describe the solution you'd like**
Show how many items can be built using available resources

**Comment by abearcodes** [comment]
Implemented in 1.0.13
