### ISSUE TITLE
Favors Chest Inventory

### ISSUE THREAD

**Issue by rcayne** [abearcodes/Valheim#42]
**Mod**: Crafting With Containers / Simple Recycling

**Mod Version**: 

**Describe the bug**
Cannot load items to charcoal kiln/smelter from inventory. Items must be in chest.

**How To Reproduce**
1. First do ''
2. Then do '....'
3. After doing '....'
4. Then this bug happens

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Additional details**
Are you running any other mods? If yes, please list them here.

**Comment by abearcodes** [comment]
Fixed in 1.0.14. Please reopen if this reoccurs.
