### ISSUE TITLE
Unable to add Flax to the Spinning Wheel

### ISSUE THREAD

**Issue by normous** [abearcodes/Valheim#43]
**Mod**: Crafting With Containers

**Mod Version**: 1.0.13

**Describe the bug**
Unable to add Flax to the Spinning Wheel

**How To Reproduce**
1. Have Flax in inventory
2. Press 'E' to add to Spinning Wheel
3. Game states "You don't have and processable items"
4. Get the following error in BepInEx log:
    `[Debug  :Crafting with Containers] Found item . Container? False`

**Expected behavior**
Add Flax to Spinning Wheel as normal

**Additional details**
Disabled mod, able to add Flax to Spinning Wheel without 1.0.13 running.

--EDIT:  Upon further testing, this only happens when Flax is in player inventory.  Built a chest, put the flax inside,  and was able to feed the Spinning Wheel from the chest.

**Comment by BridgeGuy** [comment]
I'm having similar issues with adding wood to kiln and any ore to smelters/blast furnace.

**Comment by normous** [comment]
> 
> 
> I'm having similar issues with adding wood to kiln and any ore to smelters/blast furnace.

I don't believe this is the same issue. On the latest version adding wood to kilns and ore to smelters/blast furnaces work fine for me.
