### ISSUE TITLE
Blast furnace doesn't accept black scrap metal I'm carrying

### ISSUE THREAD

**Issue by cj360** [abearcodes/Valheim#45]
**Mod**: Crafting With Containers

**Mod Version**: 
1.0.13

Load of black scrap metal in my inventory blast furnace isn't taking it at all.

**How To Reproduce**
1. Emptied a Fuling village
2. Returned to base to smelt ore 
3. Furnace says no smelt-able items despite having 30 pieces of black scrap metal on hand.

Coal was still able to be taken from my nearby reinforced chest

denikson-BepInExPack_Valheim-5.4.800
Xenofell-Skillful-0.3.0
Xenofell-PreWorkout-0.2.0
abearcodes-CraftingWithContainers-1.0.13
BasilPanda-NoStamCosts-0.1.2
xAfflict-NonrestrictedPortals-1.2.1
Khairex-Useful_Trophies-1.1.0
1010101110-multiplayerboatdamage-0.0.1
exel80-MapTeleporter-1.0.0
Tekla-RemoveDeathPins-5.4.800
MahLanna-PlantingPlus-1.0.2
Xenofell-ImNoMasochist-0.2.1
Xenofell-Jeeves-0.2.0
AdditionalRecipes-1.0.2
combatFrontFacing-1.2.0
CropReplant-2.1.1
PickableTimeFix-1.0.1

**Comment by abearcodes** [comment]
Fixed in 1.0.14. Please reopen if this reoccurs.
