### ISSUE TITLE
Mod stopped working

### ISSUE THREAD

**Issue by marlon-ss** [abearcodes/Valheim#47]
**Mod**: Crafting With Containers / Simple Recycling

**Mod Version**: 

**Describe the bug**
The mod isn't getting the items from the container

**Additional details**

other mods i use:

*ExploreTogether
*BetterUi
*MultiCraft
*EquipmentAndQuickSlots
*InventorySorting
*FasterTeleportation
* Add_All_Fuel_And_Ore_For_Smelter_Charcoalkiln_etc
* FermenterPercentage
* Quick_Deposit
* HoldAttack
* Clock

**Comment by PhirisIricadros** [comment]
It seems to be an issue with the Equipment and Quick Slots mod recent update. This issue was addressed in another thread

**Comment by marlon-ss** [comment]
> It seems to be an issue with the Equipment and Quick Slots mod recent update. This issue was addressed in another thread
Thank you

**Comment by marlon-ss** [comment]
> It seems to be an issue with the Equipment and Quick Slots mod recent update. This issue was addressed in another thread

Thank you
