### ISSUE TITLE
CwC Incompatible with Equipment and Quick Slots plugin ?

### ISSUE THREAD

**Issue by hawnt42** [abearcodes/Valheim#48]
**[Crafting with Containers 1.0.13]**

**Issue**
Incompatibility with [Equipment and Quick Slots 2.0.2]

Multiple Issues:
- Loading coal into smelter does not work from nearby containers, and adding coal with coal in inventory removes all coal and counts as 1 in the smelter.
- Crafting with items in nearby containers does not work, although the containers are tagged when enabling debug.
- Loading of wood into Kiln does work, however it does not use any wood from any nearby containers, nor from inventory.  Magic!

**Loaded Plugins**
[Info   :   BepInEx] Loading [Crafting with Containers 1.0.13]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 1.0.0]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.0.2]

**Comment by abearcodes** [comment]
Thank you for your report! I'll test these use cases, although this ticket itself duplicates of #43, #44 and #45, so I'll be closing it! Please keep track of the issue in the other tickets.
