### ISSUE TITLE
Items not being pulled from chests nearby or showing as available in crafting stations as of current build in multiplayer.

### ISSUE THREAD

**Issue by williethewolf** [abearcodes/Valheim#49]
**Mod**: Crafting With Containers 

**Mod Version**: 1.0.13

**Describe the bug**
While playing multiplayer dedicated server. Only player with the mod. It was working fine up to this update.
Materials in containers not showing as available in crafting stations. Fire pits and hearths not pulling wood from containers. Klin works pulling wood. Using default mod settings. 

**How To Reproduce**

Mods installed:
    BepInExPack_Valheim by denikson
    CraftingWithContainers by abearcodes
    BetterUI by Masa
    EquipmentAndQuickSlots by RandyKnapp
    SimpleRecycling by abearcodes
    FermenterPercentage by LTmadness
    ValheimBrawler by ceko
    Build_In_Dungeons by LottieVixen
    Better_Stamina by bakaspaceman
    ValheimFaveServers by L41rx
    PickableTimeFix by Nexus
    InstantMonsterLootDrop by Nexus
    MultiCraft by MaxiMods
    QuickConnect by bdew
    FarmGrid by Nexus
    BetterAutoRun by nearbear
    BiggerBoatMapExploreRadius by nearbear
    EmoteWheel by virtuaCode
    FirstPerson by Masa
    PlantingPlus by MahLanna

1. First do 'fill chest'
2. Then do 'go to crafting station'
3. After doing '....'
4. Then this bug happens

Tried installing and uninstalling.

**Expected behavior**
Items to be pulled from chest

**Comment by BitFlipp3r** [comment]
Same here. Happened after upgrading EquipmentAndQuickSlots to v2. Disabled EAQS (Warning: unequipp items first). Working again.

**Comment by abearcodes** [comment]
Confirmed E&QS issue. Thank you all for your reports, they help! Please use #44 for further discussions.

1.0.14 will also revert the networking back to the old system. Fix introduced in 1.0.13 would now require all clients to have the mod installed. I need more time to work on a proper fix for negotiation between modded and unmodded clients.
