### ISSUE TITLE
Resources disappearing 

### ISSUE THREAD

**Issue by occelot666** [abearcodes/Valheim#51]
I updated to the latest version and ever since then when i dismantle items i lose half the resources so i removed the mod and the bug went so i re-added the mod and the bug instantly came back.  Its not like the old bug that people had when dismantling when they only received 1 of an item it is always half

**Comment by DennisGehrke** [comment]
So I think my issue corresponds with this issue, so I comment here:

Ever since I craft any item, it uses the double amount of resources out of my inventory, not even using the container resources, but does not give the double crafted items. Its just a waste of resources.

**Comment by kabessaun** [comment]
I had the same problem, to craft something , it uses double of resources

**Comment by occelot666** [comment]
I have looked at what you said and tested and it is as you say using double resources to craft i had'nt noticed it was that way around until you said

**Comment by xrande** [comment]
Can confirm. It uses double resources when crafting. And it doesn't seem to take materials from containers anymore.

**Comment by abearcodes** [comment]
What other mods you are running? This isn't caused by CwC itself and is related to mod compatibility. Most likely #44, but please do post a list of all mods you are running to make sure

**Comment by DennisGehrke** [comment]
Hey, it could be related to #44 as I use this mod as well. My list is the following:

ExploreTogether by Rolo
CraftingWithContainers by abearcodes
BepInExPack_Valheim by denikson
SimpleRecycling by abearcodes
CustomSlotItemLib by nearbear
BetterUI by Masa
EquipmentAndQuickSlots by RandyKnapp
FarmGrid by Nexus
Quick_Deposit by MaGic
QuickConnect by bdew
AutoRepair by Tekla
WishboneSlot by nearbear
PaddlePower by mgway
ValheimArmorstand by ceko
PlantingPlus by xXPancakeXx
MultiCraft by MaxiMods
multiplayerboatdamage by 1010101110
TrashItems by virtuaCode

**Comment by abearcodes** [comment]
Confirmed E&QS issue. Thank you all for your reports, they help! Please use #44 for further discussions.
