### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Ezzatoninan** [abearcodes/Valheim#52]
**Mod**: Crafting With Containers / Simple Recycling

**abearcodes-CraftingWithContainers-1.0.13**: 

**Describe the bug**
will take ores for smelter, and wood from container for coal maker but nothing else works, And here's the BIG BAD THING is whatever else you build be it house part, resin to refills torches or make things it takes or uses 2x of that item so to refill a torch its only 4 resin so if you go to refill it uses 2 each time you click to refill torch so you use 8 resin when it only needs 4, instead of 1 at a time, same goes for building house parts need 4 wood it uses 8 or making weapons armor, etc... found this out way too late and blew through so much of my supplies BIG BUG!

**How To Reproduce**
1. First do '..make or refil anything.'
2. Then do '..check your count..'
3. After doing '..scream and get mad..'
4. Then this bug happens

**Expected behavior**
A description of what you expected to happen.
Normal crafting or refilling

**Screenshots**

**Additional details**
Other mods I am running

abearcodes-CraftingWithContainers-1.0.13
abearcodes-SimpleRecycling-0.0.13
denikson-BepInExPack_Valheim-5.4.800
Masa-BetterUI-1.6.0
RandyKnapp-EquipmentAndQuickSlots-2.0.2
Rolo-ExploreTogether-1.2.2
Smallo-CraftingStationsLevelBasedBuildRange-1.5.0
Tekla-AutoRepair-5.4.800
xAfflict-NonrestrictedPortals-1.2.1

**Comment by xrande** [comment]
Can confirm. It uses double resources when crafting. And it doesn't seem to take materials from containers anymore.

**Comment by abearcodes** [comment]
Confirmed E&QS issue. Thank you all for your reports, they help! Please use #44 for further discussions.
