### ISSUE TITLE
Suggestion: Build From Cart/Storage

### ISSUE THREAD

**Issue by Sythalin** [abearcodes/Valheim#6]
Any chance of being able to implement the ability to build from carts/boats/storage?  For example, would be awesome if we could load up a cart full of wood, park it next to a workbench, and be able to place floors/walls/etc. while pulling from the cart/storage.

**Comment by jmcquillan** [comment]
I'd love to see BuildWithContainers

**Comment by abearcodes** [comment]
Building from carts should already work as long as the cart is not moving. Boats are planned. 

Building from Containers is now implemented, but not yet released. If you'd like to test it, try this pre-release:
https://github.com/abearcodes/Valheim/releases/tag/v1.0.4-beta.1

**Comment by jmcquillan** [comment]
I tried out v1.0.4-beta.1 and it seemed to work great!

**Comment by abearcodes** [comment]
Building from storage, carts and boats is released as of 1.0.4. 

As of 1.0.7 (just released), if you are not the last "owner" of a boat or ship (based on game logic), it will not consider that container. Therefore, pulling a cart and crafting should work ok. Ships... eh... Depends. If you are the first person that stepped on the ship, you are the owner. If somebody else opened the container on the ship, then they are the owner. 

I do have a fix queued that will make all of these issues go away, but I don't have the time to work on it right now. 

Closing this issue. Please reopen if this still does not cover what is expected.
