### ISSUE TITLE
NullReferenceException when loading plugin.

### ISSUE THREAD

**Issue by carrotowl** [abearcodes/Valheim#9]
```
[Info   :   BepInEx] Loading [Crafting with Containers 1.0.5]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ABearCodes.Valheim.CraftingWithContainers.CompatibilityFixer.RemoveAllPrefixesFrom_InventoryGui_SetupRequirement (HarmonyLib.Harmony harmony) (at <005461a4e2524f92b523dfcf0cfd2b69>:0)
ABearCodes.Valheim.CraftingWithContainers.CompatibilityFixer.Apply (HarmonyLib.Harmony harmony) (at <005461a4e2524f92b523dfcf0cfd2b69>:0)
ABearCodes.Valheim.CraftingWithContainers.Plugin.Awake () (at <005461a4e2524f92b523dfcf0cfd2b69>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```

Mod list:
[Info   :   BepInEx] Loading [Crafting with Containers 1.0.5]
[Info   :   BepInEx] Loading [Faster Teleportation 0.3.1.0]
[Info   :   BepInEx] Loading [SkToolbox 1.5.0.0]
[Info   :   BepInEx] Loading [Dream's Data Rate Modifier 1.0.0.0]
[Info   :   BepInEx] Loading [BetterUI 1.3.1]
[Info   :   BepInEx] Loading [FirstPerson 1.0.2]
[Info   :   BepInEx] Loading [MapSyncPlugin 1.0.0.0]
[Info   :   BepInEx] Loading [FortifySkills 1.0.0.0]
[Info   :   BepInEx] Loading [Better Discord Presence 1.2.1]
[Info   :   BepInEx] Loading [InteractWhileBuilding 0.0.3]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 1.0.3]
[Info   :   BepInEx] Loading [AutoRepair 1.0.0.0]
[Info   :   BepInEx] Loading [PreWorkout 0.2]
[Info   :   BepInEx] Loading [RememberIPDamnit 0.2]
[Info   :   BepInEx] Loading [Skillful 0.3]

**Comment by Manuelwb287** [comment]
I have the same issue.
I've tried disabling all mods except this one and still same issue.

**Comment by abearcodes** [comment]
Yup, my bad. I rushed the workaround for Valheim Plus and didn't cover the case for when it's not present. v1.0.6 released to Thunderstore. Please reopen if this keeps happening.
